
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19042 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Der Buildvorgang wurde am 04.10.2023 13:31:05 gestartet.
      Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" auf Knoten "1" (Standardziele).
      PrepareForBuild:
        Das Verzeichnis "Debug\\" wird erstellt.
        Das Verzeichnis "Debug\\CompilerIdC.tlog\\" wird erstellt.
      InitializeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Die Datei "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird gelöscht.
        Aktualisieren des Timestamps von "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Die Erstellung von Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" ist abgeschlossen (Standardziele).
      
      Der Buildvorgang wurde erfolgreich ausgeführt.
          0 Warnung(en)
          0 Fehler
      
      Verstrichene Zeit 00:00:00.85
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build/CMakeFiles/3.27.6/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Der Buildvorgang wurde am 04.10.2023 13:31:07 gestartet.
      Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" auf Knoten "1" (Standardziele).
      PrepareForBuild:
        Das Verzeichnis "Debug\\" wird erstellt.
        Das Verzeichnis "Debug\\CompilerIdCXX.tlog\\" wird erstellt.
      InitializeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Die Datei "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" wird gelöscht.
        Aktualisieren des Timestamps von "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Die Erstellung von Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" ist abgeschlossen (Standardziele).
      
      Der Buildvorgang wurde erfolgreich ausgeführt.
          0 Warnung(en)
          0 Fehler
      
      Verstrichene Zeit 00:00:00.67
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build/CMakeFiles/3.27.6/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build\uf00d/CMakeFiles/CMakeScratch/TryCompile-xtczyb"
      binary: "C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build\uf00d/CMakeFiles/CMakeScratch/TryCompile-xtczyb"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build/CMakeFiles/CMakeScratch/TryCompile-xtczyb'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_8aff8.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        Der Buildvorgang wurde am 04.10.2023 13:31:08 gestartet.
        Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-xtczyb\\cmTC_8aff8.vcxproj" auf Knoten "1" (Standardziele).
        PrepareForBuild:
          Das Verzeichnis "cmTC_8aff8.dir\\Debug\\" wird erstellt.
          Das Verzeichnis "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-xtczyb\\Debug\\" wird erstellt.
          Das Verzeichnis "cmTC_8aff8.dir\\Debug\\cmTC_8aff8.tlog\\" wird erstellt.
        InitializeBuildStatus:
          "cmTC_8aff8.dir\\Debug\\cmTC_8aff8.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8aff8.dir\\Debug\\\\" /Fd"cmTC_8aff8.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\cmake-3.27.6-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++-Optimierungscompiler Version 19.33.31630 für x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8aff8.dir\\Debug\\\\" /Fd"cmTC_8aff8.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\cmake-3.27.6-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-xtczyb\\Debug\\cmTC_8aff8.exe" /INCREMENTAL /ILK:"cmTC_8aff8.dir\\Debug\\cmTC_8aff8.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build?/CMakeFiles/CMakeScratch/TryCompile-xtczyb/Debug/cmTC_8aff8.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build?/CMakeFiles/CMakeScratch/TryCompile-xtczyb/Debug/cmTC_8aff8.lib" /MACHINE:X64  /machine:x64 cmTC_8aff8.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_8aff8.vcxproj -> C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-xtczyb\\Debug\\cmTC_8aff8.exe
        FinalizeBuildStatus:
          Die Datei "cmTC_8aff8.dir\\Debug\\cmTC_8aff8.tlog\\unsuccessfulbuild" wird gelöscht.
          Aktualisieren des Timestamps von "cmTC_8aff8.dir\\Debug\\cmTC_8aff8.tlog\\cmTC_8aff8.lastbuildstate".
        Die Erstellung von Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-xtczyb\\cmTC_8aff8.vcxproj" ist abgeschlossen (Standardziele).
        
        Der Buildvorgang wurde erfolgreich ausgeführt.
            0 Warnung(en)
            0 Fehler
        
        Verstrichene Zeit 00:00:00.52
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/cmake-3.27.6-windows-x86_64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build\uf00d/CMakeFiles/CMakeScratch/TryCompile-5itqo7"
      binary: "C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build\uf00d/CMakeFiles/CMakeScratch/TryCompile-5itqo7"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build/CMakeFiles/CMakeScratch/TryCompile-5itqo7'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_d0753.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        Der Buildvorgang wurde am 04.10.2023 13:31:09 gestartet.
        Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-5itqo7\\cmTC_d0753.vcxproj" auf Knoten "1" (Standardziele).
        PrepareForBuild:
          Das Verzeichnis "cmTC_d0753.dir\\Debug\\" wird erstellt.
          Das Verzeichnis "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-5itqo7\\Debug\\" wird erstellt.
          Das Verzeichnis "cmTC_d0753.dir\\Debug\\cmTC_d0753.tlog\\" wird erstellt.
        InitializeBuildStatus:
          "cmTC_d0753.dir\\Debug\\cmTC_d0753.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d0753.dir\\Debug\\\\" /Fd"cmTC_d0753.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\cmake-3.27.6-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++-Optimierungscompiler Version 19.33.31630 für x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d0753.dir\\Debug\\\\" /Fd"cmTC_d0753.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\cmake-3.27.6-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-5itqo7\\Debug\\cmTC_d0753.exe" /INCREMENTAL /ILK:"cmTC_d0753.dir\\Debug\\cmTC_d0753.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build?/CMakeFiles/CMakeScratch/TryCompile-5itqo7/Debug/cmTC_d0753.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/kadechur.l.FUTRONIC/Desktop/Codefor-practice/build?/CMakeFiles/CMakeScratch/TryCompile-5itqo7/Debug/cmTC_d0753.lib" /MACHINE:X64  /machine:x64 cmTC_d0753.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_d0753.vcxproj -> C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-5itqo7\\Debug\\cmTC_d0753.exe
        FinalizeBuildStatus:
          Die Datei "cmTC_d0753.dir\\Debug\\cmTC_d0753.tlog\\unsuccessfulbuild" wird gelöscht.
          Aktualisieren des Timestamps von "cmTC_d0753.dir\\Debug\\cmTC_d0753.tlog\\cmTC_d0753.lastbuildstate".
        Die Erstellung von Projekt "C:\\Users\\kadechur.l.FUTRONIC\\Desktop\\Codefor-practice\\build?\\CMakeFiles\\CMakeScratch\\TryCompile-5itqo7\\cmTC_d0753.vcxproj" ist abgeschlossen (Standardziele).
        
        Der Buildvorgang wurde erfolgreich ausgeführt.
            0 Warnung(en)
            0 Fehler
        
        Verstrichene Zeit 00:00:00.68
        
      exitCode: 0
...
